postgres_config:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "dbagent"

llm:
  openai:
    model: "openai/gpt-4o"
    api_key: "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"
    base_url: "https://models.github.ai/inference"

database:
  num_retry: 3
  DIALECT: "postgres"