version: "3.9"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: agent_app
    volumes:
      - ./src/configs/config_container.yaml:/app/configs/config.yaml
    depends_on:
      - db
    env_file:
      - ./src/.env
    ports:
      - 8080:8080
  db:
    image: pgvector/pgvector:pg16
    container_name: agent_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbagent
      POSTGRES_DB: postgres
    volumes:
      - ./database/data_source:/import
      - ./database/init:/docker-entrypoint-initdb.d  
