version: "3.8"

networks:
  public: {}
  private:
    internal: true

services:
  app:
    image: ai_agent_app:1.0
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: agent_app
    volumes:
      - ./src/configs/config_container.yaml:/app/configs/config.yaml
    depends_on:
      - db
    env_file:
      - ./src/.env
    ports:
      - 8080:8080
    networks:
      - private
      - public
  db:
    image: postgres:18
    container_name: agent_db
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbagent
      POSTGRES_DB: postgres
    volumes:
      - ./database/data_source:/import
      - ./database/init:/docker-entrypoint-initdb.d 
    networks:
      - private
    deploy:
      replicas: 2
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    command: server --console-address ":9001" /data

volumes:
  minio_storage: