version: "3.9"

services:
  postgres:
    image: postgres
    container_name: agent_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbagent
      POSTGRES_DB: postgres
    volumes:
      - ./data_source:/import
