postgres_config:
  host: "db"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "dbagent"

llm:
  openai:
    model: "model"
    api_key: "api_key"
    base_url: "base_url"

database:
  num_retry: 3
  DIALECT: "postgres"